### ISSUE TITLE
RuntimeError: CUDA error: invalid argument when using xformers

### ISSUE THREAD

**Issue by vmajor** [huggingface/diffusers#1946]
### Describe the bug

When trying to run train_dreambooth.py with --enable_xformers_memory_efficient_attention the process exits with this error:

```
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Steps:   0%|                                                                                                                          | 0/400 [00:07<?, ?it/s]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/*****/anaconda3/envs/sd-gpu/bin/accelerate:8 in <module>                                  │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/*****/anaconda3/envs/sd-gpu/lib/python3.10/site-packages/accelerate/commands/accelerate_c │
│ li.py:45 in main                                                                                 │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/*****/anaconda3/envs/sd-gpu/lib/python3.10/site-packages/accelerate/commands/launch.py:11 │
│ 04 in launch_command                                                                             │
│                                                                                                  │
│   1101 │   elif defaults is not None and defaults.compute_environment == ComputeEnvironment.AMA  │
│   1102 │   │   sagemaker_launcher(defaults, args)                                                │
│   1103 │   else:                                                                                 │
│ ❱ 1104 │   │   simple_launcher(args)                                                             │
│   1105                                                                                           │
│   1106                                                                                           │
│   1107 def main():                                                                               │
│                                                                                                  │
│ /home/*****/anaconda3/envs/sd-gpu/lib/python3.10/site-packages/accelerate/commands/launch.py:56 │
│ 7 in simple_launcher                                                                             │
│                                                                                                  │
│    564 │   process = subprocess.Popen(cmd, env=current_env)                                      │
│    565 │   process.wait()                                                                        │
│    566 │   if process.returncode != 0:                                                           │
│ ❱  567 │   │   raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)       │
│    568                                                                                           │
│    569                                                                                           │
│    570 def multi_gpu_launcher(args):                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
```

### Reproduction

accelerate launch train_dreambooth.py --pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4 --instance_data_dir=./inputs   --output_dir=./outputs  --instance_prompt="a photo of sks dog" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=5e-6 --lr_scheduler="constant" --lr_warmup_steps=0  --max_train_steps=400 --enable_xformers_memory_efficient_attention

### System Info

- `diffusers` version: 0.12.0.dev0
- Platform: Linux-5.15.79.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.10.8
- PyTorch version (GPU?): 1.13.0 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 0.15.0
- Accelerate version: not installed
- xFormers version: 0.0.15.dev395+git.7e05e2c
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: single GPU

**Comment by davidpfahler** [comment]
Same error running on Runpod. It seems like the pipeline **without** prior preservation is broken. It works if you use the example with prior preservation: https://github.com/huggingface/diffusers/blob/aba2a65d6ab47c0d1c12fa47e9b238c1d3e34512/examples/dreambooth/README.md#training-with-prior-preservation-loss

**Comment by davidpfahler** [comment]
This might be an upstream bug in xformers https://github.com/facebookresearch/xformers/issues/563

**Comment by hafriedlander** [comment]
Related issue https://github.com/huggingface/diffusers/issues/1829

**Comment by hafriedlander** [comment]
@davidpfahler in the meantime, using this to enable xformers instead of the built-in enable xformers method should work:

https://github.com/cloneofsimo/lora/blob/master/lora_diffusion/xformers_utils.py#L42

**Comment by patrickvonplaten** [comment]
cc @patil-suraj

**Comment by patil-suraj** [comment]
Could be an issue with `xformers` version, I have been using the `xformers` pre-release and it seems to be working without any issues https://pypi.org/project/xformers/#history

**Comment by TsykunovDmitriy** [comment]
Thanks for the tip. I had the same issue. I solved it by installing [this](https://pypi.org/project/xformers/0.0.16rc425/) xformers pre-release package as @patil-suraj said and updating pytorch version to 1.13.1+cu117.

**Comment by hafriedlander** [comment]
@patil-suraj this is arch specific. What arch are you testing on? It's possible they've fixed it, but the bugs are still open

https://github.com/facebookresearch/xformers/issues/517
https://github.com/facebookresearch/xformers/issues/628

(I'll check latest xformers in a bit, but I already have a fix for myself.)

**Comment by patil-suraj** [comment]
So far, I've only tried it on A100 and T4

**Comment by hafriedlander** [comment]
The two where definitely it works :). The arch I know has issues is SM8x except SM80 (so 30xx and 40xx mostly). 

(Although it looks like there's a bit more action in the xformers repo, so this might actually get fixed upstream at some point now.)

**Comment by USBhost** [comment]
> Thanks for the tip. I had the same issue. I solved it by installing [this](https://pypi.org/project/xformers/0.0.16rc425/) xformers pre-release package as @patil-suraj said and updating pytorch version to 1.13.1+cu117.

This worked on my A6000. pytorch 1.13.1 is a must as I installed xformers 436 for 1.12.1 and I still got that error.

**Comment by gleb-akhmerov** [comment]
> Thanks for the tip. I had the same issue. I solved it by installing [this](https://pypi.org/project/xformers/0.0.16rc425/) xformers pre-release package as @patil-suraj said and updating pytorch version to 1.13.1+cu117.

While I'm no longer getting an error, it looks like the model doesn't learn anymore. The images which are generated after the training are the same as before it.

However, I've found an older version of xformers which works just fine (with torch 1.12.1): https://github.com/facebookresearch/xformers/commit/0bad001ddd56c080524d37c84ff58d9cd030ebfd. This seems to be the last commit that works for me, as far as I can tell from a few tests using later commits.

Since it was not easy to find the correct package versions, I want to share my findings.

GPU: 3060
CUDA version: 11.8
OS: Arch Linux

My installation process:

```bash
cd examples/dreambooth
pip install \
    -r requirements.txt \
    git+https://github.com/huggingface/diffusers.git@7c82a16fc14840429566aec40eb9e65aa57005fd \
    torch==1.12.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 \
    bitsandbytes==0.35.1 \
    triton==2.0.0.dev20221202 \
    scikit-learn \
    datasets \
    ninja
pip install git+https://github.com/facebookresearch/xformers.git@0bad001ddd56c080524d37c84ff58d9cd030ebfd
```

If nvcc is not on `$PATH` (like on Arch Linux), you can change the last line and specify the path to cuda like this:
```bash
PATH="$PATH:/opt/cuda/bin" pip install git+https://github.com/facebookresearch/xformers.git@0bad001ddd56c080524d37c84ff58d9cd030ebfd
```

- `torch` **must** be `1.12.1` for this xformers version
- specifying `cu116` was necessary for me since I have cuda 11.8 and I was getting an error about version mismatch between torch and cuda during xformers building. For cuda 10, it'll probably work with just `torch==1.12.1` and without `--extra-index-url`
- `ninja` is installed to build xformers faster
- `bitsandbytes` must be `0.35` because of [this](https://github.com/ShivamShrirao/diffusers/pull/178). Also, training with `0.35.4` makes the model generate blue noise for me, while `0.35.1` works fine.

**Comment by EandrewJones** [comment]
I too have been running into issues with xFormers on A10G (aws g5 instance) for training textual inversion, not dreambooth (though same issues would likely apply). The environment is containerized (only showing essential lines below):

```
FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04

# CUDA xformers build args
ENV TORCH_CUDA_ARCH_LIST = "8.0;8.6"

#
# Deep learning training and inference dependencies
#
RUN pip install -qq -U git+https://github.com/EandrewJones/diffusers
RUN pip install -q -U --pre triton
RUN pip install -q \
    ninja \
    torch==1.13.1 \
    torchvision==0.14.1 \
    accelerate==0.12.0 \
    # mlflow==2.1.1 \
    transformers \
    datasets \
    ftfy \
    pathlib
RUN pip install --upgrade \
    scipy
# RUN conda install -y xformers=0.0.16.dev430+git.bac8718 xformers/label/dev
RUN pip install -v -U git+https://github.com/facebookresearch/xformers.git@0bad001ddd56c080524d37c84ff58d9cd030ebfd
# RUN pip install -v xformers==0.0.17.dev435

Rest of file...
```

Somewhere between 100-300 steps into training, loss goes to NaN. I know the issue is xFormers because it runs fine w/o it. No C++ errors, just silent failure.

Installations I've tried (pytorch 1.13.1 and cuda 11.6/7 for all):
- Every pip release > 0.0.13 (including the one @patil-suraj mentioned above)
- Conda install from dev and main (used different base image `pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime`)
- Compiling from scratch on both base images (ran into issues mentioned by OP)

The weird thing is `python -m xFormers` always indicates success:
```
memory_efficient_attention.cutlassF:               available
memory_efficient_attention.cutlassB:               available
memory_efficient_attention.flshattF:               available
memory_efficient_attention.flshattB:               available
memory_efficient_attention.smallkF:                available
memory_efficient_attention.smallkB:                available
memory_efficient_attention.tritonflashattF:        available
memory_efficient_attention.tritonflashattB:        available
swiglu.fused.p.cpp:                                available
is_triton_available:                               True
is_functorch_available:                            False
pytorch.version:                                   1.13.1
pytorch.cuda:                                      available
gpu.compute_capability:                            8.6
gpu.name:                                          NVIDIA A10G
build.info:                                        available
build.cuda_version:                                1106
build.python_version:                              3.10.9
build.torch_version:                               1.13.1
build.env.TORCH_CUDA_ARCH_LIST:                    5.0+PTX 6.0 6.1 7.0 7.5 8.0 8.6
build.env.XFORMERS_BUILD_TYPE:                     None
build.env.XFORMERS_ENABLE_DEBUG_ASSERTIONS:        None
build.env.NVCC_FLAGS:                              None
build.env.XFORMERS_PACKAGE_FROM:                   None
source.privacy:                                    open source
```

**Comment by EandrewJones** [comment]
I tried this and the 0.17 pre-release.

I'll report in xformers, but I believe I found a related issue there
already.

Best

Evan Jones
Website: www.ea-jones.com

**Comment by USBhost** [comment]
Before the bot makes this issue disappear is it resolved?

**Comment by EandrewJones** [comment]
yes
Best

Evan Jones
Website: www.ea-jones.com
