### ISSUE TITLE
RuntimeError: CUDA error: invalid argument when train_dreambooth.py

### ISSUE THREAD

**Issue by sharkDDD** [huggingface/diffusers#3325]
### Describe the bug

I followed the instructions to train the dreambooth model, but the RuntimeError: CUDA error: invalid argument occured at accelerator.backward(loss)
My device is RTX-3090, and I will appreciate it if some one can help me solve the problem.

### Reproduction

  warnings.warn(
05/03/2023 20:30:07 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'dynamic_thresholding_ratio', 'variance_type', 'thresholding', 'clip_sample_range', 'sample_max_value', 'prediction_type'} was not found in config. Values will be initialized to default values.
{'norm_num_groups'} was not found in config. Values will be initialized to default values.
{'class_embed_type', 'time_embedding_type', 'class_embeddings_concat', 'conv_out_kernel', 'encoder_hid_dim', 'resnet_out_scale_factor', 'use_linear_projection', 'timestep_post_act', 'upcast_attention', 'only_cross_attention', 'dual_cross_attention', 'num_class_embeds', 'addition_embed_type_num_heads', 'resnet_time_scale_shift', 'cross_attention_norm', 'time_cond_proj_dim', 'time_embedding_dim', 'time_embedding_act_fn', 'conv_in_kernel', 'projection_class_embeddings_input_dim', 'mid_block_type', 'resnet_skip_time_act', 'mid_block_only_cross_attention', 'addition_embed_type'} was not found in config. Values will be initialized to default values.
05/03/2023 20:30:14 - INFO - __main__ - ***** Running training *****
05/03/2023 20:30:14 - INFO - __main__ -   Num examples = 200
05/03/2023 20:30:14 - INFO - __main__ -   Num batches each epoch = 200
05/03/2023 20:30:14 - INFO - __main__ -   Num Epochs = 4
05/03/2023 20:30:14 - INFO - __main__ -   Instantaneous batch size per device = 1
05/03/2023 20:30:14 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
05/03/2023 20:30:14 - INFO - __main__ -   Gradient Accumulation steps = 1
05/03/2023 20:30:14 - INFO - __main__ -   Total optimization steps = 800
Steps:   0%|                                                                                                                                                                       | 0/800 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_dreambooth.py", line 1102, in <module>
    main(args)
  File "train_dreambooth.py", line 1034, in main
    accelerator.backward(loss)
  File "/home/wzq/anaconda3/envs/dreambooth/lib/python3.8/site-packages/accelerate/accelerator.py", line 1683, in backward
    loss.backward(**kwargs)
  File "/home/wzq/anaconda3/envs/dreambooth/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/wzq/anaconda3/envs/dreambooth/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### System Info

- `diffusers` version: 0.17.0.dev0
- Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- PyTorch version (GPU?): 2.0.0+cu117 (True)
- Huggingface_hub version: 0.14.1
- Transformers version: 4.28.1
- Accelerate version: 0.18.0
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by mu94-csl** [comment]
This is also failing for me on a single A10 GPU with a similar error message (no particular details are provided). 
My environment is also similar, except for python is 3.10.11.
To reproduce, just follow the dreambooth tutorial with original instructions.
Enabling xformers support surprisingly makes it work

**Comment by sharkDDD** [comment]
> This is also failing for me on a single A10 GPU with a similar error message (no particular details are provided). My environment is also similar, except for python is 3.10.11. To reproduce, just follow the dreambooth tutorial with original instructions. Enabling xformers support surprisingly makes it work

Thanks for your help, I enable the xformers and then the error disappeared, but it is really weired and I think this indeed a bug.

**Comment by sharkDDD** [comment]
> @sharkDDD could you please add a easy-to-run, minimally reproducible code snippet?

I following the tutorial of https://huggingface.co/docs/diffusers/v0.16.0/en/training/dreambooth#dreambooth and run train_dreambooth.py
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="./dog"
export CLASS_DIR="path_to_class_images"
export OUTPUT_DIR="path_to_saved_model"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of sks dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=800

then the error appeared, but when I enable the xformers, it worked, I did not figure out why the CUDA error appeared and hope it will be solved.

**Comment by szjiozi** [comment]
> > This is also failing for me on a single A10 GPU with a similar error message (no particular details are provided). My environment is also similar, except for python is 3.10.11. To reproduce, just follow the dreambooth tutorial with original instructions. Enabling xformers support surprisingly makes it work
> 
> Thanks for your help, I enable the xformers and then the error disappeared, but it is really weired and I think this indeed a bug.

What do you mean by enabling xformers? import it?

**Comment by zhanghongruiupup** [comment]
> > > This is also failing for me on a single A10 GPU with a similar error message (no particular details are provided). My environment is also similar, except for python is 3.10.11. To reproduce, just follow the dreambooth tutorial with original instructions. Enabling xformers support surprisingly makes it work
> > 
> > 
> > Thanks for your help, I enable the xformers and then the error disappeared, but it is really weired and I think this indeed a bug.
> 
> What do you mean by enabling xformers? import it?

Command  add： -- enable_ Xforms_ Memory_ Effective_ Attention
