### ISSUE TITLE
Typical CUDA Memory usage for `UNet2DConditionModel` 

### ISSUE THREAD

**Issue by ovshake** [huggingface/diffusers#350]
Hi, 
Thanks for this wonderful and easy-to-use repository. I would like to know the typical VRAM usage of `UNet2DConditionModel` if I use the default parameters for one forward and backward pass. I am using a batch size of 1 with mixed precision but I am still getting 
```
*** RuntimeError: CUDA out of memory. Tried to allocate 4.00 GiB (GPU 0; 23.70 GiB total capacity; 16.11 GiB already allocated; 1.91 GiB free; 20.11 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
``` 
I have 24GB of VRAM available. This is my model definition 
```
model =  UNet2DConditionModel(sample_size=128,
                            in_channels=3,
                            out_channels=3,
                            layers_per_block=2,
                            cross_attention_dim=768).cuda()
``` 
I am wondering if there is any bug in my code, which is resulting in high VRAM usage. 
Thanks!

**Comment by patrickvonplaten** [comment]
With 24GB you should definitely be able to get your model running (e.g. I just tried it on my 24GB GPU and it works). 

From the error message above it seems like some other code is already taking 16GB of your GPU. 

Could you copy-paste a full code snippet below that we I could run on GPU to see if I can reproduce your error? :-) 

```python
model =  UNet2DConditionModel(sample_size=128,
                            in_channels=3,
                            out_channels=3,
                            layers_per_block=2,
                            cross_attention_dim=768).cuda()
```

consumes way less than 24GB VRAM for me

**Comment by ovshake** [comment]
Thanks for the reply. I have made a [gist](https://gist.github.com/ovshake/362591dcb38bd7471df2de55f715cf6e). You can run this by simply `python main.py`. I have attached two files. You can place `06528_00.jpg` in `/path/of/your/choice/cloth/06528_00.jpg` and `06528_00.np.gz` in `/path/of/your/choice/clip_txt_embeddings/06528_00.np.gz
`. In the gist, replace [Line 80](https://gist.github.com/ovshake/362591dcb38bd7471df2de55f715cf6e#file-train-py-L80) with `/path/of/your/choice/`. I hope you are able to reproduce the issue with this snippet. 
![06528_00](https://user-images.githubusercontent.com/22028532/188325289-4b36b4f2-3db9-471c-8c3f-a1db6b40d9c6.jpg)
[06528_00.np.gz](https://github.com/huggingface/diffusers/files/9485132/06528_00.np.gz)

**Comment by ovshake** [comment]
Hi @patrickvonplaten, sorry to bug, did you get a chance to look at this?

**Comment by patrickvonplaten** [comment]
Hey @ovshake,

Sorry for being so late here! I see you were training a model. Yeah at the moment we're getting indeed also some OOMs here because memory usage increases a lot! 

Two things:
- Could you try enabling attention slicing? This should significantly reduce memory usage: https://twitter.com/PatrickPlaten/status/1567185296453779456 . You would need to add this line right after instantiating your UNet2DConditionModel
- We're currently working on enabling `gradient_checkpointing` which should reduce memory usage by 4x - I hope that it'll get merged by Friday. 

Apart from this your script already looks very efficient. One more tip would be to replace Adam with https://github.com/TimDettmers/bitsandbytes (that should save an additional 20% memory)

**Comment by ovshake** [comment]
No worries, thanks for the response. Let me try the things that you mentioned. I am closing the issue now.
