### ISSUE TITLE
SD XL Inpaint: Out of memory on 6 GB VRAM

### ISSUE THREAD

**Issue by tin2tin** [huggingface/diffusers#4788]
### Describe the bug

I'm trying to implement SD XL inpaint in my [add-on](https://github.com/tin2tin/Generative_AI) for Blender. I'm on 6 GB VRAM, and so far I've been able to make ex. txt2vid and img2vid and vid2vid working. I've tried model_cpu_offload and vae_slicing without success. As it is properly not a bug making it impossible to do inpaint on 6 GB VRAM, maybe it could be considered to implement ex. forward_curling for this function, or something else to make inpainting work on 6 GB VRAM?

### Reproduction

Run this code on 6 GB VRAM:

From docs (+model_cpu_offload and vae_slicing)
```
import torch
from diffusers import StableDiffusionXLInpaintPipeline
from diffusers.utils import load_image

pipe = StableDiffusionXLInpaintPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16, variant="fp16", use_safetensors=True
)
pipe.enable_model_cpu_offload()
pipe.enable_vae_slicing()

img_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo.png"
mask_url = "https://raw.githubusercontent.com/CompVis/latent-diffusion/main/data/inpainting_examples/overture-creations-5sI6fQgYIuo_mask.png"

init_image = load_image(img_url).convert("RGB")
mask_image = load_image(mask_url).convert("RGB")

prompt = "A majestic tiger sitting on a bench"
image = pipe(prompt=prompt, image=init_image, mask_image=mask_image, num_inference_steps=50, strength=0.80).images[0]
```

### Logs

```shell
File "C:\Users\XXXXX\AppData\Roaming\Python\Python310\site-packages\diffusers\models\resnet.py", line 639, in forward
    output_tensor = (input_tensor + hidden_states) / self.output_scale_factor
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 6.00 GiB total capacity; 5.11 GiB already allocated; 0 bytes free; 5.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

Windows 11
Diffusers 0.20.1 Alpha

**Comment by patrickvonplaten** [comment]
Can you try using a more memory optimized VAE: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix

To see if this could fix it?

**Comment by tin2tin** [comment]
Unfortunately it doesn't. Its seems like it is already breaking when importing SDXL with StableDiffusionXLInpaintPipeline. So this is before a refiner is imported. 

(Newer, seen that sdxl-vae-fp16-fix before. I'll try it out on some of the other functions. Do you think it could have a positive effect on all fp16? Even text to video?)

**Comment by Vargol** [comment]
Note that Diffusers sneakily upcasts the vae to fp32 if you don't tell it not too with force_upcast=False
The built in SDXL vae is actually broken at 16bit, the numbers can go too high and become NaN's leading to black images.
That's why sdxl-vae-fp16-fix is needed 
e.g.

vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16, force_upcast=False)

As an aside the upcast confused me as to why everyone was saying it broke at fp16, but its was working for me.
Turns out I was the only one using diffusers directly everyone else was using GUI's :-) .

**Comment by tin2tin** [comment]
Thank you Vargol. Unfortunately doesn't this solve the memory problem either. 

I wonder why importing "stabilityai/stable-diffusion-xl-base-1.0" through StableDiffusionXLInpaintPipeline is so much more heavy on the vram?

Anything else I can try or do?

**Comment by patrickvonplaten** [comment]
> Note that Diffusers sneakily upcasts the vae to fp32 if you don't tell it not too with force_upcast=False
> 
> ```
> vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", 
>                                       torch_dtype=torch.float16, 
>                                       force_upcast=False)
> ```
> 
> The built in SDXL vae is actually broken at 16bit, the numbers can go too high and become NaN's leading to black images. That's why sdxl-vae-fp16-fix is needed As an aside the upcast confused me as to why everyone was saying it broke at fp16, but its was working for me. Turns out I was the only one using diffusers directly everyone else was using GUI's :-) .

@Vargol not that you don't have to pass `force_upcast=False` - it's down automatically see here: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/blob/97b09ba005d991b0aa24996f1457909b97482caf/config.json#L31

So the following should be preferred:
```py
vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", 
                                      torch_dtype=torch.float16)
```
