### ISSUE TITLE
Training Controlnet SDXL distributed gives out-of-memory errors

### ISSUE THREAD

**Issue by miquel-espinosa** [huggingface/diffusers#4925]
### Describe the bug

Hi.
I am running the Controlnet SDXL example as it is shown in the `examples` section [[example-link](https://github.com/huggingface/diffusers/blob/main/examples/controlnet/README_sdxl.md)].
I am unable to reproduce the results in a SLURM managed environment, where I have 8 A100 40GB GPUs in the same node (which is much more than in the example).
I always get an OOM error (see below).
On the other hand, running the **exact** same script with SD1.5 model (and its script) runs correctly, and I can increase the `batch_size` to much higher values.

### Reproduction

Below, I provide the `.sh` file I use to launch the job in the SLURM cluster (note that it is only requesting 1 node with 8 gpus). This script, in my case, it will always throw and OOM error. If I change the model to SD1.5 instead of SDXL, it will run without any problem.

```
#!/bin/bash
##----------------------- Start job description -----------------------
#SBATCH --time=24:00:00
#SBATCH --output=slurm-%x.%j.out
#SBATCH --partition=partition
#SBATCH --account=account
#SBATCH --gres=gpu:8
#SBATCH --cpus-per-task=16
#SBATCH --job-name=train-sd-xl-circles
#SBATCH --mem=400G
##------------------------ End job description ------------------------

# Environment
module purge && source ~/virtualenvs/diffusers/bin/activate

export MODEL_DIR="stabilityai/stable-diffusion-xl-base-1.0"
export OUTPUT_DIR="/out_dir"
export CACHE_DIR=/tmp

export NUM_GPUS=8
export NUM_WORKERS=16

accelerate launch --mixed_precision="fp16" --num_processes $NUM_GPUS --multi_gpu train_controlnet_sdxl.py \
 --pretrained_model_name_or_path=$MODEL_DIR \
 --output_dir=$OUTPUT_DIR \
 --dataset_name=fusing/fill50k \
 --mixed_precision="fp16" \
 --resolution=256 \
 --learning_rate=1e-5 \
 --max_train_steps=15000 \
 --validation_image "./conditioning_image_1.png" "./conditioning_image_2.png" \
 --validation_prompt "red circle with blue background" "cyan circle with brown floral background" \
 --validation_steps=100 \
 --cache_dir=$CACHE_DIR \
 --dataloader_num_workers=$NUM_WORKERS \
 --tracker_project_name="sd-xl-circles" \
 --train_batch_size=1 \
 --gradient_accumulation_steps=4 \
 --report_to="wandb" \
 --seed=42
```

### Logs

```shell
09/06/2023 16:18:14 - INFO - __main__ -   Gradient Accumulation steps = 4
09/06/2023 16:18:14 - INFO - __main__ -   Total optimization steps = 15000
Steps:   0%|          | 0/15000 [00:12<?, ?it/s, loss=0.0259, lr=1e-5]Traceback (most recent call last):
  File "train_controlnet_sdxl.py", line 1236, in <module>
    main(args)
  File "train_controlnet_sdxl.py", line 1164, in main
    optimizer.step()
  File "/home/users/mespi/virtualenvs/diffusers/lib/python3.8/site-packages/accelerate/optimizer.py", line 134, in step
    self.scaler.step(self.optimizer, closure)
  File "/home/users/mespi/virtualenvs/diffusers/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 374, in step
    retval = self._maybe_opt_step(optimizer, optimizer_state, *args, **kwargs)
  File "/home/users/mespi/virtualenvs/diffusers/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 290, in _maybe_opt_step
    retval = optimizer.step(*args, **kwargs)
  File "/home/users/mespi/virtualenvs/diffusers/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 69, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/users/mespi/virtualenvs/diffusers/lib/python3.8/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/users/mespi/virtualenvs/diffusers/lib/python3.8/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/users/mespi/virtualenvs/diffusers/lib/python3.8/site-packages/torch/optim/adamw.py", line 171, in step
    adamw(
  File "/home/users/mespi/virtualenvs/diffusers/lib/python3.8/site-packages/torch/optim/adamw.py", line 321, in adamw
    func(
  File "/home/users/mespi/virtualenvs/diffusers/lib/python3.8/site-packages/torch/optim/adamw.py", line 566, in _multi_tensor_adamw
    denom = torch._foreach_add(exp_avg_sq_sqrt, eps)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 39.39 GiB total capacity; 37.63 GiB already allocated; 9.94 MiB free; 38.28 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

- `diffusers` version: 0.21.0.dev0
- Platform: Linux-3.10.0-1160.76.1.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.12
- PyTorch version (GPU?): 2.0.1+cu117 (True)
- Huggingface_hub version: 0.16.2
- Transformers version: 4.30.2
- Accelerate version: 0.20.3
- xFormers version: 0.0.20
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: yes

### Who can help?

@patrickvonplaten @sayakpaul @williamberman @yiyixuxu

**Comment by sayakpaul** [comment]
Have you tried enabling xformers during training?

**Comment by miquel-espinosa** [comment]
yes, I still get OOM error when adding the `--enable_xformers_memory_efficient_attention` flag.

**Comment by sayakpaul** [comment]
For the SLURM and advanced multi-GPU settings, I would recommend following: https://github.com/huggingface/diffusers/blob/controlnet_webdatasets/examples/controlnet/train_controlnet_webdatasets.py.

**Comment by patrickvonplaten** [comment]
cc @williamberman @patil-suraj can you check here?

**Comment by xinsir6** [comment]
I meet the same question, the controlnet sdxl always report OOM error whatever batchsize or resolution i set, there may be some problem with it, can anyone have a look?

**Comment by wade3han** [comment]
same here, we met same issue with a100 40gb.

**Comment by wade3han** [comment]
> For the SLURM and advanced multi-GPU settings, I would recommend following: https://github.com/huggingface/diffusers/blob/controlnet_webdatasets/examples/controlnet/train_controlnet_webdatasets.py.

Also tried this one, the code is not working; the training stucks, GPUs are not working. (8 A100s, slurm)

**Comment by sayakpaul** [comment]
That we cannot reproduce as we have used that script quite extensively on our cluster and it scales pretty well.

**Comment by wade3han** [comment]
weird, I just tried with single A100-40GB and it works, but with 8 GPUs it does not work

**Comment by garychan22** [comment]
> I meet the same question, the controlnet sdxl always report OOM error whatever batchsize or resolution i set, there may be some problem with it, can anyone have a look?

I have also met this problem whatever batchsize or resolution i set, have you resolved this problem?

**Comment by sayakpaul** [comment]
Have you given https://github.com/huggingface/diffusers/blob/controlnet_webdatasets/examples/controlnet/train_controlnet_webdatasets.py a try?

**Comment by rockmanxyj** [comment]
> > For the SLURM and advanced multi-GPU settings, I would recommend following: https://github.com/huggingface/diffusers/blob/controlnet_webdatasets/examples/controlnet/train_controlnet_webdatasets.py.
> 
> Also tried this one, the code is not working; the training stucks, GPUs are not working. (8 A100s, slurm)

Same issue here, may I ask how you resolved it? I am also using a single A100-40GB.

**Comment by ZichengDuan** [comment]
Hi, did you solve the problem? I am encountering the same problem on A100. The code raises OOM on both single A100 40G and multiple ones.

**Comment by xuan97916** [comment]
You can add `--use_8bit_adam` and ` --enable_xformers_memory_efficient_attention` flag, it works for me. The VRAM usage for each card is about 35GB when set `--train_batch_size=1` and `--resolution=1024`.
