### ISSUE TITLE
Can't train in cuda by pytorch's `backward`.

### ISSUE THREAD

**Issue by ChengAoShen** [huggingface/diffusers#5821]
### Describe the bug

To transfer the pre-trained model to my personal research project that uses the diffusion model to fusion emoji, I used `UNet2DConditionModel` as my denoising model. I didn't use accelerate due to complexity, and I used  pytorch to train the model. 
My code works well on my Mac with mps, but the problem occurs when I use a server with CUDA. The problems happen during backward loss.

### Reproduction

Here is a simple demo to reproduce the problems
```
import torch
import torch.nn.functional as F
from diffusers import UNet2DConditionModel
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = UNet2DConditionModel(
    sample_size=64,
    in_channels=4,
    out_channels=4,
    cross_attention_dim=768).to(device).train()
image = torch.rand(1,4,64,64).to(device)
condition = torch.rand(1,77,768).to(device)
time=torch.rand(1).to(device)

optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
predict = model(image,time,condition)
loss = F.mse_loss(predict.sample, image)
loss.backward()  #! bug happen here
optimizer.step()
optimizer.zero_grad()

```

when I want to backward and get the loss, the cuda will arise bug said above.

### Logs

```shell
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

- `diffusers` version: 0.23.0
- Platform: Linux-5.4.0-100-generic-x86_64-with-glibc2.17
- Python version: 3.8.10
- PyTorch version (GPU?): 2.0.0+cu118 (True)
- Huggingface_hub version: 0.19.3
- Transformers version: not installed
- Accelerate version: not installed
- xFormers version: not installed
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

### Who can help?

@DN6 @yiyixuxu

**Comment by pedrogengo** [comment]
I ran your script here and it didn't raise any error. Can you run `nvidia-smi` and post the screenshot here?

**Comment by ChengAoShen** [comment]
Of course, here is the screenshot of my `nvidia-smi`, and I also post the screenshot of the running process of this script, I hope it can help to analyze the problems. 
<img width="683" alt="image" src="https://github.com/huggingface/diffusers/assets/68673559/545b0b0f-5d1f-4479-a1b2-d73b4cbb1fbd">
<img width="1252" alt="image" src="https://github.com/huggingface/diffusers/assets/68673559/4f775f93-d664-4a6f-af4e-6aadd92ee7c1">

**Comment by pedrogengo** [comment]
Can you try `pip install https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp38-cp38-linux_x86_64.whl` to see if installing a binary for cuda 12 solves your problem?

**Comment by ChengAoShen** [comment]
Thanks, I will try it later. Actually, I use the `accelerate` to train my model in the same environment, and it works well.

**Comment by Sylvie-X** [comment]
have you solved this bug? I get the same problem when I run the codes under examples\dreambooth and I use accelerate. It's confusing that It's ok if enable_xformers_memory_efficient_attention else goes wrong.
