### ISSUE TITLE
svd can be run in pytorch 2.x version, but running in Pytorch 1.13.1 version will appear OOM

### ISSUE THREAD

**Issue by buxianggaimingzi** [huggingface/diffusers#7629]
### Describe the bug

I use diffusers 0.27.2 version to run svd, input the image size (1024, 576), When I use pytorch2.0.1 svd can run normally, and the VRAM usage is only about 12GB, which is far less than the maximum VRAM of my machine(80G), but when I use pytorch1.13.1 svd appears OOM. So I don't know if it's the pytorch, xformers, triton versions or the support in diffusers

### Reproduction

svd code follow https://huggingface.co/docs/diffusers/using-diffusers/text-img2vid
```
import torch
from diffusers import StableVideoDiffusionPipeline
from diffusers.utils import load_image, export_to_video

pipeline = StableVideoDiffusionPipeline.from_pretrained(
    "stabilityai/stable-video-diffusion-img2vid-xt", torch_dtype=torch.float16, variant="fp16"
)
pipeline.enable_model_cpu_offload()

image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png")
image = image.resize((1024, 576))

generator = torch.manual_seed(42)
frames = pipeline(image, decode_chunk_size=8, generator=generator).frames[0]
export_to_video(frames, "generated.mp4", fps=7)
```

### Logs

```shell
Traceback (most recent call last):
  File "test_svd.py", line 17, in <module>
    frames = pipe(image, decode_chunk_size=8, generator=generator).frames[0]
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/diffusers/pipelines/stable_video_diffusion/pipeline_stable_video_diffusion.py", line 523, in __call__
    noise_pred = self.unet(
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/diffusers/models/unets/unet_spatio_temporal_condition.py", line 434, in forward
    sample, res_samples = downsample_block(
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/diffusers/models/unets/unet_3d_blocks.py", line 2183, in forward
    hidden_states = attn(
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/diffusers/models/transformers/transformer_temporal.py", line 351, in forward
    hidden_states = block(
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/diffusers/models/attention.py", line 329, in forward
    attn_output = self.attn1(
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 522, in forward
    return self.processor(
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 781, in __call__
    attention_probs = attn.get_attention_scores(query, key, attention_mask)
  File "/home/chenyifei/anaconda3/envs/test/lib/python3.8/site-packages/diffusers/models/attention_processor.py", line 602, in get_attention_scores
    attention_scores = torch.baddbmm(
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 39.55 GiB (GPU 0; 79.33 GiB total capacity; 44.57 GiB already allocated; 33.37 GiB free; 45.06 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

pytorch2.0.1 env:
- `diffusers` version: 0.27.2
- Platform: Linux-5.4.54-1.0.0.std7c.el7.2.x86_64-x86_64-with-glibc2.17
- Python version: 3.11.5
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.22.2
- Transformers version: 4.36.2
- Accelerate version: 0.25.0
- xFormers version: 0.0.22
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

pytorch1.13.1 env:
- `diffusers` version: 0.27.2
- Platform: Linux-5.4.54-1.0.0.std7c.el7.2.x86_64-x86_64-with-glibc2.17
- Python version: 3.8.19
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- Huggingface_hub version: 0.22.2
- Transformers version: 4.36.2
- Accelerate version: 0.25.0
- xFormers version: 0.0.16
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by standardAI** [comment]
PyTorch 2.x comes with a memory-efficient attention but I wouldn't expect that much difference 🤔.

**Comment by buxianggaimingzi** [comment]
Thanks to your reply, xformers 0.0.16 seems to be the top version that supports pytorch 1.x. I also tried pytorch1.13.1 without xformers, but OOM still appears

**Comment by standardAI** [comment]
When I try with your exact code in Colab with `PyTorch==1.13.1`, it tries to allocate 39 GiB and OOM. But when I add `pipeline.enable_xformers_memory_efficient_attention()` with `xFormers==0.0.16`, it works. Could you please be sure you activated xFormers in this way?

**Comment by buxianggaimingzi** [comment]
Oh sorry, that's my fault. I used xformers incorrectly earlier. After adding```pipeling.enable_xformers_memory_efficient_attention()```, it works, thank u very much~
