### ISSUE TITLE
playground  cuda error

### ISSUE THREAD

**Issue by Honey-666** [huggingface/diffusers#8523]
https://github.com/huggingface/diffusers/blob/896fb6d8d7c10001eb2a92568be7b4bd3d5ddea3/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py#L728

When I initialize without using `to('cuda')`, the model exists in the cpu, so here self.device gets the handle on the cpu, refer to the code above, whether we change it to `device`

## error msg:
      init_latents = (init_latents - latents_mean) * self.vae.config.scaling_factor / latents_std
      RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

## os:
diffusers==diffusers-0.28.2

## this is my code:

```
import torch
from PIL import Image
from diffusers import StableDiffusionXLImg2ImgPipeline, EDMDPMSolverMultistepScheduler

sd_xl_path = '../models/Stable-diffusion/playground-v2.5-xl-aesthetic'
img_path = './image_1.png'

pipe = StableDiffusionXLImg2ImgPipeline.from_pretrained(sd_xl_path,
                                                        torch_dtype=torch.float16,
                                                        add_watermarker=False,
                                                        )

pipe.enable_model_cpu_offload()
pipe.scheduler = EDMDPMSolverMultistepScheduler.from_config(pipe.scheduler.config, use_karras_sigmas=True)

image = Image.open(img_path)

images = pipe(prompt='a beautiful girl',
              image=image,
              guidance_scale=3.0,
              num_inference_steps=30,
              strength=0.5
              ).images
print(images)

```

**Comment by tolgacangoz** [comment]
Could you just upgrade `diffusers` to the latest stable version?

**Comment by yiyixuxu** [comment]
hi @Honey-666 

I think it should be `device` instead of `self.device` here - do you want to give it a try and if it works, maybe open a PR for us? 🤗
```python
 latents_mean = latents_mean.to(device=self.device, dtype=dtype) 
```

**Comment by Honey-666** [comment]
> Could you just upgrade `diffusers` to the latest stable version?

I tried to upgrade to the latest version and he had the same problem

**Comment by Honey-666** [comment]
> hi @Honey-666
> 
> I think it should be `device` instead of `self.device` here - do you want to give it a try and if it works, maybe open a PR for us? 🤗
> 
> ```python
>  latents_mean = latents_mean.to(device=self.device, dtype=dtype) 
> ```

Yes I have tried this modification and it works fine. yeah, I'd love to do that

**Comment by tolgacangoz** [comment]
Where does `playground-v2.5-xl-aesthetic` come from? I couldn't reproduce with `playgroundai/playground-v2.5-1024px-aesthetic`. They are different I guess.

**Comment by haofanwang** [comment]
Agree with @tolgacangoz, cannot reproduce this error with `playgroundai/playground-v2.5-1024px-aesthetic`.

**Comment by Honey-666** [comment]
> Agree with @tolgacangoz, cannot reproduce this error with `playgroundai/playground-v2.5-1024px-aesthetic`.

of course I don't always get to reproduce it, but it always comes when I don't expect it
![debug_image](https://github.com/huggingface/diffusers/assets/76274942/1a32e0a5-ce75-4853-baf3-d33814eba0b2)

**Comment by tolgacangoz** [comment]
> Could you just upgrade `diffusers` to the latest stable version?

When I said this yesterday, I reproduced with `diffusers==0.28.2` but couldn't with `diffusers==0.29.0`; then I directly said "Could you just upgrade it?". But now, I am able to reproduce this issue with both versions.

**Comment by yiyixuxu** [comment]
well we should use `self.device` here anyway, which does not work with offloading  
`self._execution_device` does, i.e. the `device` argument passed to this function
https://github.com/huggingface/diffusers/blob/25d7bb3ea65bb6f79056252584e24eb545c5eb18/src/diffusers/pipelines/pipeline_utils.py#L985

**Comment by sayakpaul** [comment]
Is this fixed, @yiyixuxu?

**Comment by Honey-666** [comment]
It seems to have the same problem here, https://github.com/huggingface/diffusers/blob/e15a8e7f17529ebf4029eed07f982e14c7560546/src/diffusers/loaders/ip_adapter.py#L215

#### error msg:
    `RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same`

**Comment by sayakpaul** [comment]
Gently pinging @yiyixuxu here.

**Comment by Honey-666** [comment]
> @Honey-666 I think the one with the `load_ip_adapter` is not so much of a problem because you need to run that before `enable_model_cpu_offload` anyway

Thank you. Yes, I put the `load_ip_adapter` in front of the `enable_model_cpu_offload` and it works fine
But then I have to load `image_encoder` when I initialize pipe. Assuming I initialize pipe without loading it, if I decide that `ip_adapter_image` is not empty in the `__call__` argument, Loading the `load_ip_adapter` will cause the above error
