### ISSUE TITLE
JAX / Flax pipeline: "Ran out of memory in memory space hbm." on TPU v2-8

### ISSUE THREAD

**Issue by skirsten** [huggingface/diffusers#856]
### Describe the bug

I followed the blog post [here](https://huggingface.co/blog/stable_diffusion_jax) on `diffusers==0.5.1`. I am running inside a Colab TPU instance so I added [this snippet](https://github.com/google/jax#pip-installation-colab-tpu):

```py
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
```

but now I get the following error during the first JIT compilation:

```
2022-10-15 18:07:41.780474: W external/org_tensorflow/tensorflow/compiler/xla/python/tpu_driver/client/tpu_client.cc:617] TPU Execute is taking a long time. This might be due to a deadlock between multiple TPU cores or a very slow program.
Traceback (most recent call last):
  File "bulk_infer_jax.py", line 162, in <module>
    main()
  File "bulk_infer_jax.py", line 102, in main
    images = pipe(prompt_ids, p_params, rng, jit=True).images
  File "/usr/local/lib/python3.7/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_flax_stable_diffusion.py", line 275, in __call__
    self, prompt_ids, params, prng_seed, num_inference_steps, height, width, guidance_scale, latents, debug
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/api.py", line 2204, in cache_miss
    out_tree, out_flat = f_pmapped_(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/api.py", line 2083, in pmap_f
    global_arg_shapes=p.global_arg_shapes_flat)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 2062, in bind
    return map_bind(self, fun, *args, **params)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 2094, in map_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 2065, in process
    return trace.process_map(self, fun, tracers, params)
  File "/usr/local/lib/python3.7/dist-packages/jax/core.py", line 701, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/usr/local/lib/python3.7/dist-packages/jax/interpreters/pxla.py", line 951, in xla_pmap_impl
    *abstract_args)
  File "/usr/local/lib/python3.7/dist-packages/jax/linear_util.py", line 306, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.7/dist-packages/jax/interpreters/pxla.py", line 1198, in parallel_callable
    pmap_executable = pmap_computation.compile()
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/profiler.py", line 313, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/jax/interpreters/pxla.py", line 1481, in compile
    self._executable = PmapExecutable.from_hlo(self._hlo, **self.compile_args)
  File "/usr/local/lib/python3.7/dist-packages/jax/interpreters/pxla.py", line 1615, in from_hlo
    pci.backend, xla_computation, compile_options, host_callbacks)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 1057, in compile_or_get_cached
    host_callbacks)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/profiler.py", line 313, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/jax/_src/dispatch.py", line 996, in backend_compile
    return backend.compile(built_c, compile_options=options)
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: XLA:TPU compile permanent error. Ran out of memory in memory space hbm. Used 9.45G of 7.48G hbm. Exceeded hbm capacity by 1.97G.

Total hbm usage >= 9.97G:
    reserved        530.00M 
    program           7.46G 
    arguments         1.99G 

Output size 1.50M; shares 0B with arguments.

Program hbm requirement 7.46G:
    global           100.0K
    scoped            81.0K
    HLO temp          7.46G (94.2% utilization: Unpadded (7.01G) Padded (7.44G), 0.0% fragmentation (0B))

  Largest program allocations in hbm:

  1. Size: 512.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/while/body/FlaxUNet2DConditionModel/down_blocks_0/attentions_0/transformer_blocks_0/attn1/b i d, b j d->b i j/jit(_einsum)/dot_general[dimension_numbers=(((2,), (2,)), ((0,), (0,))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.7/contextlib.py" source_line=74
     Shape: bf16[16,4096,4096]{1,2,0:T(8,128)(2,1)}
     Unpadded size: 512.00M
     XLA label: fusion.6667 = fusion(bitcast.2826, bitcast.2830), kind=kOutput, calls=fused_computation.4974.clone
     Allocation type: HLO temp
     ==========================

  2. Size: 512.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/while/body/FlaxUNet2DConditionModel/down_blocks_0/attentions_1/transformer_blocks_0/attn1/b i d, b j d->b i j/jit(_einsum)/dot_general[dimension_numbers=(((2,), (2,)), ((0,), (0,))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.7/contextlib.py" source_line=74
     Shape: bf16[16,4096,4096]{1,2,0:T(8,128)(2,1)}
     Unpadded size: 512.00M
     XLA label: fusion.6724 = fusion(bitcast.2865, bitcast.2869), kind=kOutput, calls=fused_computation.4976.clone
     Allocation type: HLO temp
     ==========================

  3. Size: 512.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/while/body/FlaxUNet2DConditionModel/up_blocks_3/attentions_0/transformer_blocks_0/attn1/b i d, b j d->b i j/jit(_einsum)/dot_general[dimension_numbers=(((2,), (2,)), ((0,), (0,))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.7/contextlib.py" source_line=74
     Shape: bf16[16,4096,4096]{1,2,0:T(8,128)(2,1)}
     Unpadded size: 512.00M
     XLA label: fusion.7565 = fusion(bitcast.3366, bitcast.3370), kind=kOutput, calls=fused_computation.5000.clone
     Allocation type: HLO temp
     ==========================

  4. Size: 512.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/while/body/FlaxUNet2DConditionModel/up_blocks_3/attentions_1/transformer_blocks_0/attn1/b i d, b j d->b i j/jit(_einsum)/dot_general[dimension_numbers=(((2,), (2,)), ((0,), (0,))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.7/contextlib.py" source_line=74
     Shape: bf16[16,4096,4096]{1,2,0:T(8,128)(2,1)}
     Unpadded size: 512.00M
     XLA label: fusion.7627 = fusion(bitcast.3406, bitcast.3410), kind=kOutput, calls=fused_computation.5002.clone
     Allocation type: HLO temp
     ==========================

  5. Size: 512.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/while/body/FlaxUNet2DConditionModel/up_blocks_3/attentions_2/transformer_blocks_0/attn1/b i d, b j d->b i j/jit(_einsum)/dot_general[dimension_numbers=(((2,), (2,)), ((0,), (0,))) precision=None preferred_element_type=None]" source_file="/usr/lib/python3.7/contextlib.py" source_line=74
     Shape: bf16[16,4096,4096]{1,2,0:T(8,128)(2,1)}
     Unpadded size: 512.00M
     XLA label: fusion.7689 = fusion(bitcast.3446, bitcast.3450), kind=kOutput, calls=fused_computation.5004.clone
     Allocation type: HLO temp
     ==========================

  6. Size: 134.00M
     Shape: bf16[512,8,67,256]{3,0,2,1:T(8,128)(2,1)}
     Unpadded size: 134.00M
     XLA label: fusion.95 = fusion(slice.684, bitcast.972), kind=kLoop, calls=fused_computation.93
     Allocation type: HLO temp
     ==========================

  7. Size: 130.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/FlaxAutoencoderKL.decode/decoder/up_blocks_2/upsamplers_0/conv/conv_general_dilated[window_strides=(1, 1) padding=((1, 1), (1, 1)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 512, 512, 256) rhs_shape=(3, 3, 256, 256) precision=None preferred_element_type=None]" source_file="/usr/local/lib/python3.7/dist-packages/flax/linen/linear.py" source_line=444
     Shape: bf16[512,8,65,256]{3,1,2,0:T(8,128)(2,1)}
     Unpadded size: 130.00M
     XLA label: fusion.55 = fusion(constant.3188, Arg_996.997, Arg_997.998, fusion.95), kind=kOutput, calls=fused_computation.55
     Allocation type: HLO temp
     ==========================

  8. Size: 130.00M
     Shape: bf16[512,1,8,65,256]{4,2,3,0,1:T(8,128)(2,1)}
     Unpadded size: 130.00M
     XLA label: fusion.123 = fusion(constant.3188, convert.5080, fusion.2677, reshape.10823, ...(+1)), kind=kLoop, calls=fused_computation.119
     Allocation type: HLO temp
     ==========================

  9. Size: 130.00M
     Shape: bf16[512,1,520,256]{3,0,2,1:T(8,128)(2,1)}
     Unpadded size: 130.00M
     XLA label: pad.64.clone = pad(copy.2544, constant.2330), padding=0_0x0_0x1_7x0_0
     Allocation type: HLO temp
     ==========================

  10. Size: 128.00M
     Shape: bf16[512,512,256]{1,2,0:T(8,128)(2,1)}
     Unpadded size: 128.00M
     XLA label: fusion.14 = fusion(copy.2275, fusion.2607), kind=kCustom, calls=fused_computation.14
     Allocation type: HLO temp
     ==========================

  11. Size: 128.00M
     Shape: bf16[512,1,512,256]{3,0,2,1:T(8,128)(2,1)}
     Unpadded size: 128.00M
     XLA label: copy.2544 = copy(bitcast.971)
     Allocation type: HLO temp
     ==========================

  12. Size: 70.00M
     Shape: bf16[256,8,35,512]{3,0,2,1:T(8,128)(2,1)}
     Unpadded size: 70.00M
     XLA label: fusion.187 = fusion(slice.670, bitcast.954), kind=kLoop, calls=fused_computation.178
     Allocation type: HLO temp
     ==========================

  13. Size: 66.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/FlaxAutoencoderKL.decode/decoder/up_blocks_1/upsamplers_0/conv/conv_general_dilated[window_strides=(1, 1) padding=((1, 1), (1, 1)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 256, 256, 512) rhs_shape=(3, 3, 512, 512) precision=None preferred_element_type=None]" source_file="/usr/local/lib/python3.7/dist-packages/flax/linen/linear.py" source_line=444
     Shape: bf16[256,8,33,512]{3,1,2,0:T(8,128)(2,1)}
     Unpadded size: 66.00M
     XLA label: fusion.118 = fusion(constant.3169, Arg_968.969, Arg_969.970, fusion.187), kind=kOutput, calls=fused_computation.116
     Allocation type: HLO temp
     ==========================

  14. Size: 66.00M
     Shape: bf16[256,1,8,33,512]{4,2,3,0,1:T(8,128)(2,1)}
     Unpadded size: 66.00M
     XLA label: fusion.270 = fusion(constant.3169, convert.5067, fusion.2618, reshape.10808, ...(+1)), kind=kLoop, calls=fused_computation.249
     Allocation type: HLO temp
     ==========================

  15. Size: 66.00M
     Shape: bf16[256,1,264,512]{3,0,2,1:T(8,128)(2,1)}
     Unpadded size: 66.00M
     XLA label: pad.50 = pad(bitcast.953, constant.2330), padding=0_0x0_0x1_7x0_0
     Allocation type: HLO temp
     ==========================

  16. Size: 65.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/FlaxAutoencoderKL.decode/decoder/up_blocks_3/resnets_0/conv_shortcut/conv_general_dilated[window_strides=(1, 1) padding=((0, 0), (0, 0)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 512, 512, 256) rhs_shape=(1, 1, 256, 128) precision=None preferred_element_type=None]" source_file="/usr/local/lib/python3.7/dist-packages/flax/linen/linear.py" source_line=444
     Shape: bf16[512,8,65,128]{3,1,2,0:T(8,128)(2,1)}
     Unpadded size: 65.00M
     XLA label: fusion.336 = fusion(Arg_1003.1004, get-tuple-element.30006, constant.3188, Arg_1002.1003), kind=kOutput, calls=fused_computation.296
     Allocation type: HLO temp
     ==========================

  17. Size: 65.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/FlaxAutoencoderKL.decode/decoder/up_blocks_3/resnets_1/conv2/conv_general_dilated[window_strides=(1, 1) padding=((1, 1), (1, 1)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 512, 512, 128) rhs_shape=(3, 3, 128, 128) precision=None preferred_element_type=None]" source_file="/usr/local/lib/python3.7/dist-packages/flax/linen/linear.py" source_line=444
     Shape: bf16[512,8,65,128]{3,1,2,0:T(8,128)(2,1)}
     Unpadded size: 65.00M
     XLA label: fusion.150 = fusion(constant.3188, get-tuple-element.30008, Arg_1010.1011, Arg_1011.1012, ...(+3)), kind=kOutput, calls=fused_computation.143
     Allocation type: HLO temp
     ==========================

  18. Size: 65.00M
     Shape: bf16[512,1,8,65,128]{4,2,3,0,1:T(8,128)(2,1)}
     Unpadded size: 65.00M
     XLA label: fusion.330 = fusion(constant.3188, convert.5093, fusion.2671, reshape.10840, ...(+1)), kind=kLoop, calls=fused_computation.290
     Allocation type: HLO temp
     ==========================

  19. Size: 65.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/FlaxAutoencoderKL.decode/decoder/up_blocks_3/resnets_0/conv1/conv_general_dilated[window_strides=(1, 1) padding=((1, 1), (1, 1)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 512, 512, 256) rhs_shape=(3, 3, 256, 128) precision=None preferred_element_type=None]" source_file="/usr/local/lib/python3.7/dist-packages/flax/linen/linear.py" source_line=444
     Shape: bf16[512,8,65,128]{3,1,2,0:T(8,128)(2,1)}
     Unpadded size: 65.00M
     XLA label: fusion.132 = fusion(constant.3188, Arg_998.999, Arg_999.1000, get-tuple-element.29629, ...(+2)), kind=kOutput, calls=fused_computation.125
     Allocation type: HLO temp
     ==========================

  20. Size: 65.00M
     Operator: op_name="pmap(_p_generate)/jit(main)/FlaxAutoencoderKL.decode/decoder/up_blocks_3/resnets_2/conv2/conv_general_dilated[window_strides=(1, 1) padding=((1, 1), (1, 1)) lhs_dilation=(1, 1) rhs_dilation=(1, 1) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 512, 512, 128) rhs_shape=(3, 3, 128, 128) precision=None preferred_element_type=None]" source_file="/usr/local/lib/python3.7/dist-packages/flax/linen/linear.py" source_line=444
     Shape: bf16[512,8,65,128]{3,1,2,0:T(8,128)(2,1)}
     Unpadded size: 65.00M
     XLA label: fusion.162 = fusion(constant.3188, get-tuple-element.30010, Arg_1018.1019, Arg_1019.1020, ...(+3)), kind=kOutput, calls=fused_computation.155
     Allocation type: HLO temp
     ==========================
```

The authors of the blog clearly state that its possible on TPU v2-8 so either its related with the Colab TPU vs TPU VM or I overlooked something.

Any help is appreciated! 

### System Info

- `diffusers` version: 0.5.1
- Platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
- Python version: 3.7.14
- PyTorch version (GPU?): 1.12.1+cu113 (False)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.1
- Using GPU in script?: no (using TPU)
- Using distributed or parallel set-up in script?: no

**Comment by pcuenca** [comment]
Hi there!

I think you need to update the jax and jaxlib versions in Colab and use the latest version of the TPU driver. This won't be necessary after Google updates the environment to see all the latest versions as default, which should presumably happen next week. For now, you need to run something like this:

```Python
!pip install --upgrade jax jaxlib
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu('tpu_driver_20221011')
```

And then install the rest of dependencies:
```
!pip install flax transformers ftfy
!pip install diffusers==0.5.1
```

Please, let us know if that works :)

**Comment by skirsten** [comment]
Works like a charm :tada:  Thank you very much!
