### ISSUE TITLE
SD3 training OOM on 4090

### ISSUE THREAD

**Issue by inspire-boy** [huggingface/diffusers#8560]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 48.00 MiB. GPU 0 has a total capacty of 23.64 GiB of which 9.69 MiB is free. Process 20296 has 23.63 GiB memory in use. Of the allocated memory 22.81 GiB is allocated by PyTorch, and 362.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation

**my params:**
  accelerate launch train_dreambooth_sd3.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --mixed_precision="fp16" \
  --instance_prompt="a photo of sks dog" \
  --resolution=1024 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --learning_rate=1e-4 \
  --report_to="wandb" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="A photo of sks dog in a bucket" \
  --validation_epochs=25 \
  --seed="42" \
  
  It make OOM. If  can someone give a lowvram example(accelerate choices included),thanks!

**Comment by tolgacangoz** [comment]
You can add `--gradient_checkpointing`, `--use_8bit_adam` flags. Also, you can try `--gradient_accumulation_steps=4`.

**Comment by tolgacangoz** [comment]
You can add `--gradient_checkpointing` and `--use_8bit_adam` flags. Also, you can try `--gradient_accumulation_steps=8`. If it still gives OOM, you can replace [`bnb.optim.AdamW8bit`](https://github.com/huggingface/diffusers/blob/f96e4a16adb4c31bab4c0a3d0d145ed2b086ecb0/examples/dreambooth/train_dreambooth_sd3.py#L1254) with [`bnb.optim.PagedAdamW8bit`](https://huggingface.co/docs/bitsandbytes/main/en/reference/optim/adamw#bitsandbytes.optim.PagedAdamW8bit) when using `--use_8bit_adam`; but this might be slower.

**Comment by bghira** [comment]
better to train a LoRA on 24G VRAM with this script, or use something else that does pre-processing eg. simpletuner

**Comment by xings19** [comment]
I also encountered this problem. In fact, the OOM was not during training, but during validation.

**Comment by xings19** [comment]
@inspire-boy Did you encounter OOM during training or during validation?

**Comment by tolgacangoz** [comment]
Did you try [PagedAdamW8bit](https://huggingface.co/docs/bitsandbytes/main/en/reference/optim/adamw#bitsandbytes.optim.PagedAdamW8bit)?

**Comment by asomoza** [comment]
yeah, with the validation prompt for the moment, you'll need at least 31GB of VRAM, with something like this:

```
accelerate launch examples/dreambooth/train_dreambooth_lora_sd3.py 
--pretrained_model_name_or_path="models/stable_diffusion_3_medium/"
 --instance_data_dir="./datasets/dog" 
--output_dir="./outputs/lora/dog/" 
--mixed_precision="fp16"
 --instance_prompt="a photo of sks dog"
 --resolution=1024 --train_batch_size=1 
--gradient_accumulation_steps=4
 --learning_rate=1e-4
 --lr_scheduler="constant" 
--optimizer="AdamW"
 --use_8bit_adam
 --lr_warmup_steps=0 
--max_train_steps=500
 --seed="42" 
```
 you can train with 21GB VRAM.

**Comment by asomoza** [comment]
Also found that you're using `--gradient_accumulation_steps=4` but not `--gradient_checkpointing` . You will still  get the OOM with it though.

**Comment by asomoza** [comment]
glad you got it working, I don't know why did you get the layers error, for me it worked from the beginning but I did use the code from some PRs that fix the loss and the gradient accumulation.

IMO the VRAM usage with validation shouldn't be that high but this is just the first iteration of the training scripts, as you can see we're still updating it with the help of the community.

Also comfyui added a commit that enables to load the diffusers SD3 lora, so it should work there too.

**Comment by C0nsumption** [comment]
Hey are you still able to get the script running? I keep having errors about the text encoder loading (made a separate issue.) The dreambooth training works but the Lora training just wont at all for me.

**Comment by qsunyuan** [comment]
I currently have four 4090 GPUs, each with a24GB of memory. Can full-finetuning (even without using some quantization tricks, train_dreambooth_lora_sd3.py or train_dreambooth_sd3.py) be distributed to run this script?

**Comment by sayakpaul** [comment]
Seems like the issue is solved. For text encoder training, we have this opened already: https://github.com/huggingface/diffusers/issues/8726
