### ISSUE TITLE
Getting OOM error when using "--caption_column="caption"".

### ISSUE THREAD

**Issue by abhicake2048** [huggingface/diffusers#8613]
### Describe the bug

DREAMBOOTH ERROR:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 28.00 MiB. GPU |
DREAMBOOTH LORA ERROR:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 12.00 MiB. GPU
in dreambooth lora training i get the error on validation.

### Reproduction

PARAMS FOR CUSTOM TRAINING

!accelerate launch train_dreambooth_sd3.py \
  --pretrained_model_name_or_path='stabilityai/stable-diffusion-3-medium-diffusers'  \
  --dataset_name="/content/drive/MyDrive/SD3_training/images" \
  --output_dir='/content/abct' \
  --mixed_precision="fp16" \
  --instance_prompt="In the style of TOK, " \
  --resolution=1024 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=8 \
  --use_8bit_adam \
  --learning_rate=1e-5 \
  --report_to="wandb" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --validation_prompt="" \
  --validation_epochs=1 \
  --caption_column='caption' \
  --num_validation_images=1 \
  --seed="0" \
  --push_to_hub
  
 FOR DREAMBOOTH LORA

!accelerate launch train_dreambooth_lora_sd3.py \
  --pretrained_model_name_or_path='stabilityai/stable-diffusion-3-medium-diffusers'  \
  --dataset_name="/content/drive/MyDrive/SD3_training/images" \
  --output_dir='/content/abct' \
  --mixed_precision="fp16" \
  --instance_prompt="In the style of TOK, " \
  --resolution=512 \
  --caption_column='caption' \
  --train_batch_size=1 \
  --use_8bit_adam \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-5 \
  --report_to="wandb" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --num_validation_images=1 \
  --validation_prompt="" \
  --validation_epochs=1 \
  --seed="0" \
  --push_to_hub

### System Info

- Platform: Linux-6.1.85+-x86_64-with-glibc2.35
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.12
- PyTorch version (GPU?): 2.3.0+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.4 (gpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Huggingface_hub version: 0.23.3
- Transformers version: 4.41.2
- Accelerate version: 0.31.0
- PEFT version: 0.7.0
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed

**Comment by asomoza** [comment]
Hi, going by your title, if you don't use `--caption_column="caption"` it works without OOM? How much VRAM do you have?

**Comment by abhicake2048** [comment]
yes it works without the `--caption_column="caption`. I am using a100 gpu.

**Comment by sayakpaul** [comment]
Can you show the full training failure log?

**Comment by sayakpaul** [comment]
Okay I see you are using Colab. How much VRAM is there? And for the same environment, does removing "caption_column" work without errors? Since it's Colab, would it be possible to provide the notebook?

**Comment by abhicake2048** [comment]
i am using 40gb a100 GPU on colab and yes it works without the "caption_column".

**Comment by sayakpaul** [comment]
Okay then I think you could provide your Colab Notebook reproducing the error. That would be helpful.

**Comment by abhicake2048** [comment]
https://colab.research.google.com/drive/16ug1LazKceqmouz_8FGJF-mrTEubwNVD?usp=sharing

**Comment by sayakpaul** [comment]
The following works for me:

```python
accelerate launch train_dreambooth_lora_sd3.py \
  --pretrained_model_name_or_path='stabilityai/stable-diffusion-3-medium-diffusers'  \
  --dataset_name="diffusers/tuxemon" \
  --output_dir="tuxemon" \
  --mixed_precision="fp16" \
  --resolution=1024 \
  --instance_prompt="okay" \
  --caption_column="blip_caption" \
  --train_batch_size=1 \
  --use_8bit_adam \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-5 \
  --report_to="wandb" \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --num_validation_images=1 \
  --validation_prompt="a tuxemon cartoon of a hedge sitting on a chair" \
  --validation_epochs=1 \
  --seed="0"
```

I couldn't use your dataset since I don't have access to it but used a dataset that closely mimics your scenario. 

@linoytsaban should we make `instance_prompt` a required argument even when `caption_column` is provided?

**Comment by sayakpaul** [comment]
@linoytsaban a gentle ping on the above comment. 

But I am going to close the issue since I was unable to reproduce. Feel free to re-open.
