### ISSUE TITLE
sdxl and contronet  must has a GPU memory more than 36G?

### ISSUE THREAD

**Issue by henbucuoshanghai** [huggingface/diffusers#9170]
### Describe the bug

https://github.com/huggingface/diffusers/blob/15eb77bc4cf2ccb40781cb630b9a734b43cffcb8/src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py
line73---line113
I run the demo with  24G GPU,  then OOM everytime.
so I must run SDXl with 48G?

@yiyixuxu @sayakpaul @DN6  tks

### Reproduction

File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1150, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB. GPU 0 has a total capacity of 23.65 GiB of which 7.56 MiB is free. Process 3431486 has 18.91 GiB memory in use. Process 3081991 has 4.72 GiB memory in use. Of the allocated memory 4.09 GiB is allocated by PyTorch, and 171.75 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

### System Info

0.28?

**Comment by DN6** [comment]
@henbucuoshanghai Could you please share the exact code you are using to run this example? And share the output of `diffusers-cli env`

**Comment by henbucuoshanghai** [comment]
i solved it

**Comment by ppbangKGT** [comment]
> i solved it

i wonder how you solved this problem. i meet the same problem.
thanks for your time.
