### ISSUE TITLE
[ERROR] CogVideoXPipeline.from_pretrained wrong device selected

### ISSUE THREAD

**Issue by loretoparisi** [huggingface/diffusers#9306]
### Describe the bug

Running the new `CogVideoXPipeline.from_pretrained` with `to` device will not send all layers to specified device:

```python
    torch.cuda.set_device( device )
    device = f'cuda:{device}'
    print(f'USING DEVICE {device} current_device:{torch.cuda.current_device()}')
    
    pipe = CogVideoXPipeline.from_pretrained(
        model_path,
        text_encoder=text_encoder,
        transformer=transformer,
        vae=vae,
        torch_dtype=dtype,
        #device_map="balanced"
    ).to(device)
```

it will run everything on `cuda:0` if `device=0` but when `device=1` it wil try to allocate some layers on `cuda:0` and other on `cuda:1` as it is clear from the `nvidia-smi` while running the example [here](https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo_quantization.py):

With `device=cuda:0` layers are allocated on GPU 0 as expected

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                    On  | 00000000:00:1B.0 Off |                    0 |
|  0%   37C    P0              61W / 300W |   9482MiB / 23028MiB |     16%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A10G                    On  | 00000000:00:1C.0 Off |                    0 |
|  0%   32C    P8              16W / 300W |      3MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A10G                    On  | 00000000:00:1D.0 Off |                    0 |
|  0%   31C    P8              16W / 300W |      3MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A10G                    On  | 00000000:00:1E.0 Off |                    0 |
|  0%   32C    P8              20W / 300W |      3MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

but executing in a 2nd shell with `device=cuda:1` allocation takes place on both GPU 0 and 1:

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.183.01             Driver Version: 535.183.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                    On  | 00000000:00:1B.0 Off |                    0 |
|  0%   62C    P0             233W / 300W |  17802MiB / 23028MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A10G                    On  | 00000000:00:1C.0 Off |                    0 |
|  0%   35C    P0              63W / 300W |  20510MiB / 23028MiB |     16%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A10G                    On  | 00000000:00:1D.0 Off |                    0 |
|  0%   32C    P8              16W / 300W |      3MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A10G                    On  | 00000000:00:1E.0 Off |                    0 |
|  0%   32C    P8              20W / 300W |      3MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

in fact this will end up with a GPU:0 OOM that it should not be used in this exection env since our device it is `cuda:1`:

```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 80.00 MiB. GPU 0 has a total capacity of 22.19 GiB of which 80.56 MiB is free. Process 289182 has 17.38 GiB memory in use. Process 290276 has 4.72 GiB memory in use. Of the allocated memory 4.48 GiB is allocated by PyTorch, and 1.81 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management 
```

### Reproduction

Run the example script [here](https://github.com/THUDM/CogVideo/blob/main/inference/cli_demo_quantization.py) in a multi-gpu environment and run it in two different shell specifying in the code the `device` variable as follows:

- device="cuda:0"
- device="cuda:1"

in the modified code as it follows:

```python
    torch.cuda.set_device( device )
    device = f'cuda:{device}'
    print(f'USING DEVICE {device} current_device:{torch.cuda.current_device()}')
    
    pipe = CogVideoXPipeline.from_pretrained(
        model_path,
        text_encoder=text_encoder,
        transformer=transformer,
        vae=vae,
        torch_dtype=dtype,
        #device_map="balanced"
    ).to(device)
```

### Logs

```shell
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 28.89it/s]
Traceback (most recent call last):
  File "cli_quantization.py.py", line 148, in <module>
    generate_video(
  File "cli_quantization.py.py", line 105, in generate_video
    video = pipe(
  File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/coder/.local/lib/python3.8/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox.py", line 629, in __call__
    prompt_embeds, negative_prompt_embeds = self.encode_prompt(
  File "/home/coder/.local/lib/python3.8/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox.py", line 297, in encode_prompt
    prompt_embeds = self._get_t5_prompt_embeds(
  File "/home/coder/.local/lib/python3.8/site-packages/diffusers/pipelines/cogvideo/pipeline_cogvideox.py", line 240, in _get_t5_prompt_embeds
    prompt_embeds = self.text_encoder(text_input_ids.to(device))[0]
  File "/home/coder/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/coder/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/coder/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 164, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "/home/coder/.local/lib/python3.8/site-packages/accelerate/hooks.py", line 698, in pre_forward
    module.to(self.execution_device)
  File "/home/coder/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2905, in to
    return super().to(*args, **kwargs)
  File "/home/coder/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/home/coder/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/coder/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/coder/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 4 more times]
  File "/home/coder/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/home/coder/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 80.00 MiB. GPU 0 has a total capacity of 22.19 GiB of which 80.56 MiB is free. Process 289182 has 17.38 GiB memory in use. Process 290276 has 4.72 GiB memory in use. Of the allocated memory 4.48 GiB is allocated by PyTorch, and 1.81 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### System Info

```
<details>
  <summary>Current environment</summary>

* CUDA:
        - GPU:
                - NVIDIA A10G
                - NVIDIA A10G
                - NVIDIA A10G
                - NVIDIA A10G
        - available:         True
        - version:           12.1
* Lightning:
        - torch:             2.4.0
        - torchao:           0.4.0
        - torchvision:       0.19.0
* Packages:
        - accelerate:        0.33.0
        - aiofiles:          22.1.0
        - aiohappyeyeballs:  2.4.0
        - aiohttp:           3.10.5
        - aiosignal:         1.3.1
        - aiosqlite:         0.18.0
        - alembic:           1.10.2
        - altair:            5.4.1
        - annotated-types:   0.7.0
        - anyio:             3.6.2
        - argon2-cffi:       21.3.0
        - argon2-cffi-bindings: 21.2.0
        - asttokens:         2.2.1
        - async-generator:   1.10
        - async-timeout:     4.0.3
        - attrs:             22.2.0
        - babel:             2.12.1
        - backcall:          0.2.0
        - beautifulsoup4:    4.11.2
        - bleach:            6.0.0
        - blinker:           1.8.2
        - boto3:             1.35.7
        - botocore:          1.35.7
        - braceexpand:       0.1.7
        - cachetools:        5.5.0
        - certifi:           2022.12.7
        - certipy:           0.1.3
        - cffi:              1.15.1
        - charset-normalizer: 3.1.0
        - click:             8.1.7
        - comm:              0.1.2
        - contourpy:         1.1.1
        - cpm-kernels:       1.0.11
        - cryptography:      39.0.2
        - cycler:            0.12.1
        - datasets:          2.21.0
        - debugpy:           1.6.6
        - decorator:         4.4.2
        - deepspeed:         0.15.0
        - defusedxml:        0.7.1
        - diffusers:         0.30.1
        - dill:              0.3.8
        - distro:            1.9.0
        - einops:            0.8.0
        - executing:         1.2.0
        - fastapi:           0.112.2
        - fastjsonschema:    2.16.3
        - ffmpy:             0.4.0
        - filelock:          3.15.4
        - fonttools:         4.53.1
        - frozenlist:        1.4.1
        - fsspec:            2024.6.1
        - gitdb:             4.0.11
        - gitpython:         3.1.43
        - gradio:            4.42.0
        - gradio-client:     1.3.0
        - greenlet:          2.0.2
        - h11:               0.14.0
        - hjson:             3.1.0
        - httpcore:          1.0.5
        - httpx:             0.27.2
        - huggingface-hub:   0.24.6
        - idna:              3.4
        - imageio:           2.34.2
        - imageio-ffmpeg:    0.5.1
        - importlib-metadata: 6.1.0
        - importlib-resources: 5.12.0
        - ipykernel:         6.21.3
        - ipython:           8.11.0
        - ipython-genutils:  0.2.0
        - jedi:              0.18.2
        - jinja2:            3.1.2
        - jiter:             0.5.0
        - jmespath:          1.0.1
        - json5:             0.9.11
        - jsonschema:        4.17.3
        - jupyter-client:    8.0.3
        - jupyter-core:      5.3.0
        - jupyter-events:    0.6.3
        - jupyter-server:    2.5.0
        - jupyter-server-fileid: 0.8.0
        - jupyter-server-terminals: 0.4.4
        - jupyter-server-ydoc: 0.8.0
        - jupyter-telemetry: 0.1.0
        - jupyter-ydoc:      0.2.3
        - jupyterhub:        3.1.1
        - jupyterlab:        3.6.2
        - jupyterlab-pygments: 0.2.2
        - jupyterlab-server: 2.20.0
        - kiwisolver:        1.4.5
        - mako:              1.2.4
        - markdown-it-py:    3.0.0
        - markupsafe:        2.1.2
        - matplotlib:        3.7.5
        - matplotlib-inline: 0.1.6
        - mdurl:             0.1.2
        - mistune:           2.0.5
        - moviepy:           1.0.3
        - mpmath:            1.3.0
        - multidict:         6.0.5
        - multiprocess:      0.70.16
        - narwhals:          1.5.5
        - nbclassic:         0.5.3
        - nbclient:          0.7.2
        - nbconvert:         7.2.10
        - nbformat:          5.7.3
        - nest-asyncio:      1.5.6
        - networkx:          3.1
        - ninja:             1.11.1.1
        - notebook:          6.5.3
        - notebook-shim:     0.2.2
        - numpy:             1.24.4
        - nvidia-cublas-cu12: 12.1.3.1
        - nvidia-cuda-cupti-cu12: 12.1.105
        - nvidia-cuda-nvrtc-cu12: 12.1.105
        - nvidia-cuda-runtime-cu12: 12.1.105
        - nvidia-cudnn-cu12: 9.1.0.70
        - nvidia-cufft-cu12: 11.0.2.54
        - nvidia-curand-cu12: 10.3.2.106
        - nvidia-cusolver-cu12: 11.4.5.107
        - nvidia-cusparse-cu12: 12.1.0.106
        - nvidia-nccl-cu12:  2.20.5
        - nvidia-nvjitlink-cu12: 12.6.20
        - nvidia-nvtx-cu12:  12.1.105
        - oauthlib:          3.2.2
        - openai:            1.42.0
        - orjson:            3.10.7
        - packaging:         23.0
        - pamela:            1.0.0
        - pandas:            2.0.3
        - pandocfilters:     1.5.0
        - parso:             0.8.3
        - pexpect:           4.8.0
        - pickleshare:       0.7.5
        - pillow:            9.5.0
        - pip:               20.0.2
        - pkgutil-resolve-name: 1.3.10
        - platformdirs:      3.1.1
        - proglog:           0.1.10
        - prometheus-client: 0.16.0
        - prompt-toolkit:    3.0.38
        - protobuf:          5.27.4
        - psutil:            5.9.4
        - ptyprocess:        0.7.0
        - pure-eval:         0.2.2
        - py-cpuinfo:        9.0.0
        - pyarrow:           17.0.0
        - pycparser:         2.21
        - pydantic:          2.8.2
        - pydantic-core:     2.20.1
        - pydeck:            0.9.1
        - pydub:             0.25.1
        - pygments:          2.14.0
        - pyopenssl:         23.0.0
        - pyparsing:         3.1.4
        - pyrsistent:        0.19.3
        - python-dateutil:   2.8.2
        - python-json-logger: 2.0.7
        - python-multipart:  0.0.9
        - pytz:              2022.7.1
        - pyyaml:            6.0
        - pyzmq:             25.0.2
        - regex:             2024.7.24
        - requests:          2.28.2
        - rfc3339-validator: 0.1.4
        - rfc3986-validator: 0.1.1
        - rich:              13.8.0
        - ruamel.yaml:       0.17.21
        - ruamel.yaml.clib:  0.2.7
        - ruff:              0.6.2
        - s3transfer:        0.10.2
        - safetensors:       0.4.4
        - semantic-version:  2.10.0
        - send2trash:        1.8.0
        - sentencepiece:     0.2.0
        - setuptools:        45.2.0
        - shellingham:       1.5.4
        - six:               1.16.0
        - smmap:             5.0.1
        - sniffio:           1.3.0
        - soupsieve:         2.4
        - sqlalchemy:        2.0.7
        - stack-data:        0.6.2
        - starlette:         0.38.2
        - streamlit:         1.38.0
        - swissarmytransformer: 0.4.12
        - sympy:             1.13.2
        - tenacity:          8.5.0
        - tensorboardx:      2.6.2.2
        - terminado:         0.17.1
        - tinycss2:          1.2.1
        - tokenizers:        0.19.1
        - toml:              0.10.2
        - tomli:             2.0.1
        - tomlkit:           0.12.0
        - torch:             2.4.0
        - torchao:           0.4.0
        - torchvision:       0.19.0
        - tornado:           6.2
        - tqdm:              4.66.5
        - traitlets:         5.9.0
        - transformers:      4.44.2
        - triton:            3.0.0
        - typer:             0.12.5
        - typing-extensions: 4.12.2
        - tzdata:            2024.1
        - urllib3:           2.2.2
        - uvicorn:           0.30.6
        - watchdog:          4.0.2
        - wcwidth:           0.2.6
        - webdataset:        0.2.96
        - webencodings:      0.5.1
        - websocket-client:  1.5.1
        - websockets:        12.0
        - wheel:             0.34.2
        - xxhash:            3.5.0
        - y-py:              0.5.9
        - yarl:              1.9.4
        - ypy-websocket:     0.8.4
        - zipp:              3.15.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.8.10
        - release:           5.10.219-208.866.amzn2.x86_64
        - version:           #1 SMP Tue Jun 18 14:00:06 UTC 2024

</details>
```

**Comment by a-r-r-o-w** [comment]
Thanks for reporting! I believe this could be because of how `enable_model_cpu_offload()` works. Refer to the docstring below and make sure to pass the correct gpu id to the function (it defaults to 0, which explains why you're seeing both GPUs being used when specifying cuda device 1):

https://github.com/huggingface/diffusers/blob/2a3fbc2cc269aa0c0d5cfdfaa3564d769d92b882/src/diffusers/pipelines/pipeline_utils.py#L953-L966

**Comment by loretoparisi** [comment]
@a-r-r-o-w I confirm it works adding:

```python
os.environ["CUDA_VISIBLE_DEVICES"] = f"{device}"
torch.cuda.set_device( device )
device = f'cuda:{device}'
pipe = CogVideoXPipeline.from_pretrained(
            model_path,
            text_encoder=text_encoder,
            transformer=transformer,
            vae=vae,
            torch_dtype=dtype,
        ).to(device)
pipe.enable_model_cpu_offload(device=device)
```
