### ISSUE TITLE
enable_vae_tiling instead leads to memory overflow

### ISSUE THREAD

**Issue by TianmengChen** [huggingface/diffusers#9648]
### Describe the bug

Using enable_vae_tiling instead causes an overflow of memory, and it is normal not to use it. This is very strange.

### Reproduction

```
from diffusers import AutoencoderKL
from diffusers.utils import  load_image, numpy_to_pil
import PIL.Image
import os
import torch
from torchvision import transforms
import numpy as np

vae = AutoencoderKL.from_pretrained("vae", device_map="auto")
vae.enable_tiling()

image_o = load_image("1.png").resize((1024,1024))
transform1 = transforms.Compose([transforms.ToTensor()])
tensor_o = torch.unsqueeze(transform1(image_o),0)

output = vae(tensor_o).sample.detach().cpu().numpy()
image = np.transpose(output, (0, 2, 3, 1))
image = numpy_to_pil(image)
image[0].save("t.png")

```

### Logs

```shell
Traceback (most recent call last):
  File "/data/chen/acer/test.py", line 16, in <module>
    output = vae(tensor_o).sample.detach().cpu().numpy()
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 465, in forward
    dec = self.decode(z).sample
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 321, in decode
    decoded = self._decode(z).sample
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 287, in _decode
    return self.tiled_decode(z, return_dict=return_dict)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 422, in tiled_decode
    decoded = self.decoder(tile)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/diffusers/models/autoencoders/vae.py", line 337, in forward
    sample = up_block(sample, latent_embeds)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 2746, in forward
    hidden_states = resnet(hidden_states, temb=temb)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/diffusers/models/resnet.py", line 363, in forward
    hidden_states = self.nonlinearity(hidden_states)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/modules/activation.py", line 393, in forward
    return F.silu(input, inplace=self.inplace)
  File "/root/miniconda3/envs/TTS/lib/python3.9/site-packages/torch/nn/functional.py", line 2072, in silu
    return torch._C._nn.silu(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 1 has a total capacty of 23.64 GiB of which 98.44 MiB is free. Including non-PyTorch memory, this process has 23.54 GiB memory in use. Of the allocated memory 23.24 GiB is allocated by PyTorch, and 98.10 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

- 🤗 Diffusers version: 0.30.3
- Platform: Linux-5.3.0-46-generic-x86_64-with-glibc2.27
- Running on Google Colab?: No
- Python version: 3.9.18
- PyTorch version (GPU?): 2.1.1 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.2
- Transformers version: 4.39.2
- Accelerate version: 1.0.0
- PEFT version: not installed
- Bitsandbytes version: not installed
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA TITAN RTX, 24576 MiB
NVIDIA TITAN RTX, 24576 MiB
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by TianmengChen** [comment]
Also, test on CPU,  enable_vae_tiling caused overflow of memory, and it is normal not to use it. This is very strange.

**Comment by a-r-r-o-w** [comment]
Try using inside of a torch.no_grad() context. Currently, it's also computing gradients so it is OOMing

**Comment by TianmengChen** [comment]
> Try using inside of a torch.no_grad() context. Currently, it's also computing gradients so it is OOMing

thanks, it works
